<a href="https://colab.research.google.com/github/MRS88/AI_course/blob/master/%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8F_07_%D0%9C%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%8B_%D0%B8_%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B8/ULTRA_LIGHT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Задача 1

* Создайте скаляр
* Создайте вектор размера 5
* Создайте матрицу размера 5х5

Выведите все три переменные на экран, если это возможно, выведите их форму и общее число элементов

In [ ]:
import numpy as np

a = 6.5
print(a, '- скаляр\n')
vec_h = np.arange(1, 6, 1).reshape(1, 5)
print(vec_h, '- горизонтальный вектор')
print(vec_h.shape, '- размер гориз.вектора')
print(vec_h.size, '- общее число элементов\n')

vec_v = vec_h.reshape(5,1)
print(vec_v, '- вертикальный вектор')
print(vec_v.shape, '- размер вертик.вектора')
print(vec_v.size, '- общее число элементов\n')

M = vec_v.dot(vec_h)
print(M, '- матрица')
print(M.shape, '- размер матрицы')
print(M.size, '- количество элементов в матрице')

6.5 - скаляр

[[1 2 3 4 5]] - горизонтальный вектор
(1, 5) - размер гориз.вектора
5 - общее число элементов

[[1]
 [2]
 [3]
 [4]
 [5]] - вертикальный вектор
(5, 1) - размер вертик.вектора
5 - общее число элементов

[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]] - матрица
(5, 5) - размер матрицы
25 - количество элементов в матрице


#Задача 2

Возьмите переменные, которые вы получили в предыдущей задаче.

* Сложите скаляр с вектором
* Умножьте скаляр на вектор
* Поделите матрицу на скаляр
* Сложите матрицу со скаляром
* Сложите матрицу с вектором - такая операция не разбиралась на занятии. Посмотрите, получится ли это сделать

In [ ]:
# сложение скаляра с вектором
print(vec_h + a, '\n')
# умножение скаляра на вектор
print(vec_h * a, '\n')
# деление матрицы на скаляр
print(M / a, '\n')
# сложение матрицы со скаляром
print(M + a, '\n')
# сложение матрицы с вектором
print(M + vec_h)

[[ 7.5  8.5  9.5 10.5 11.5]] 

[[ 6.5 13.  19.5 26.  32.5]] 

[[0.15384615 0.30769231 0.46153846 0.61538462 0.76923077]
 [0.30769231 0.61538462 0.92307692 1.23076923 1.53846154]
 [0.46153846 0.92307692 1.38461538 1.84615385 2.30769231]
 [0.61538462 1.23076923 1.84615385 2.46153846 3.07692308]
 [0.76923077 1.53846154 2.30769231 3.07692308 3.84615385]] 

[[ 7.5  8.5  9.5 10.5 11.5]
 [ 8.5 10.5 12.5 14.5 16.5]
 [ 9.5 12.5 15.5 18.5 21.5]
 [10.5 14.5 18.5 22.5 26.5]
 [11.5 16.5 21.5 26.5 31.5]] 

[[ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]
 [ 6 12 18 24 30]]


#Задача 3

Возьмите переменную с матрицей из предыдущих заданий.
С помощью соответствующих методов:

* Транспонируйте матрицу
* Найдите обратную матрицу
* Матрично умножьте саму на себя

In [ ]:
# создал новую матрицу, т.к. определитель матрицы M = 0
matrix = np.array([[0, 1, 2], [9, 2, 3], [2, 23, 4]])
print(matrix.T, '\n')
print(np.linalg.inv(matrix), '\n')
print(matrix.dot(matrix))

[[ 0  9  2]
 [ 1  2 23]
 [ 2  3  4]] 

[[-0.16223404  0.11170213 -0.00265957]
 [-0.07978723 -0.0106383   0.04787234]
 [ 0.53989362  0.00531915 -0.02393617]] 

[[ 13  48  11]
 [ 24  82  36]
 [215 140  89]]


# Задача 4

Создайте любым удобным способом "ось Х"- 1000 целых значений от 0 до 1000 не включительно. Выведите получившийся массив на экран. Напишите ответ, что вы получили: скаляр, вектор или матрицу

In [ ]:
axis_x = np.arange(0, 1000, 1)
axis_x

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18