<a href="https://colab.research.google.com/github/MRS88/AI_course/blob/master/%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8F_07_%D0%9C%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%8B_%D0%B8_%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B8/%D0%A0%D0%B0%D0%B7%D0%B1%D0%BE%D1%80_%D0%B4%D0%B7_%D0%9C%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%8B_%D0%B8_%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B8_ULTRA_LIGHT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Задача 1

* Создайте скаляр
* Создайте вектор размера 5
* Создайте матрицу размера 5х5

Выведите все три переменные на экран, если это возможно, выведите их форму и общее число элементов

In [ ]:
import numpy as np

In [ ]:
a = 1
b = np.arange(5)
c = np.random.randint(0, 10, (5,5))

In [ ]:
print(a)
print(b)
print(c)

1
[0 1 2 3 4]
[[4 5 6 4 5]
 [4 4 7 6 3]
 [7 2 1 3 7]
 [7 4 1 9 6]
 [6 0 7 1 0]]


In [ ]:
print(b.shape)
print(b.size)

(5,)
5


In [ ]:
print(c.shape)
print(c.size)

(5, 5)
25


#Задача 2

Возьмите переменные, которые вы получили в предыдущей задаче.

* Сложите скаляр с вектором
* Умножьте скаляр на вектор
* Поделите матрицу на скаляр
* Сложите матрицу со скаляром
* Сложите матрицу с вектором - такая операция не разбиралась на занятии. Посмотрите, получится ли это сделать

In [ ]:
print(a+b)
print(a*b)
print(c/a)
print(c+a)
print(c+b)

[1 2 3 4 5]
[0 1 2 3 4]
[[9. 0. 3. 7. 9.]
 [8. 2. 2. 6. 2.]
 [2. 0. 3. 8. 3.]
 [4. 3. 1. 4. 2.]
 [4. 5. 5. 2. 4.]]
[[10  1  4  8 10]
 [ 9  3  3  7  3]
 [ 3  1  4  9  4]
 [ 5  4  2  5  3]
 [ 5  6  6  3  5]]
[[ 9  1  5 10 13]
 [ 8  3  4  9  6]
 [ 2  1  5 11  7]
 [ 4  4  3  7  6]
 [ 4  6  7  5  8]]


#Задача 3

Возьмите переменную с матрицей из предыдущих заданий.
С помощью соответствующих методов:

* Транспонируйте матрицу
* Найдите обратную матрицу
* Матрично умножьте саму на себя

In [ ]:
print(c.T)
print(np.linalg.inv(c))
print(c.dot(c))

[[4 4 7 7 6]
 [5 4 2 4 0]
 [6 7 1 1 7]
 [4 6 3 9 1]
 [5 3 7 6 0]]
[[ 0.29147287 -0.51576227 -0.20465116  0.25374677  0.25891473]
 [ 0.83565891 -0.92196382 -0.54418605  0.3994832   0.22635659]
 [-0.20155039  0.38501292  0.1627907  -0.21447028 -0.0620155 ]
 [-0.3379845   0.3994832   0.08837209 -0.02118863 -0.11937984]
 [-0.35658915  0.55297158  0.44186047 -0.32816537 -0.26356589]]
[[136  68 104 105 101]
 [141  74  86 118 117]
 [106  57 109  77  66]
 [150  89 122 142 108]
 [ 80  48  44  54  85]]


# Задача 4

Создайте любым удобным способом "ось Х"- 1000 целых значений от 0 до 1000 не включительно. Выведите получившийся массив на экран. Напишите ответ, что вы получили: скаляр, вектор или матрицу

In [ ]:
x = np.arange(1000)
print(x)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

In [ ]:
#это вектор

In [ ]:
x.shape

(1000,)