<a href="https://colab.research.google.com/github/ShutTheFuckUpDonny/AI_course/blob/master/%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8F_02_Numpy/Lite.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Задача 1

1. Подгрузите файл **train_vector_1.csv** с помощью функции **np.loadtxt**. 

2. Назовите подгруженный массив my_array.

3. Убедитесь, что подгруженный массив имеет тип np.ndarray (выведите тип переменной my_array).

Ссылка на файл: https://drive.google.com/open?id=1ngnrhmoMInequrA6JyAe90lEPhcbi0iH

**Решение:**

In [ ]:
import numpy as np 
my_array = np.loadtxt('train_vector_1.csv', delimiter=',') # Создаем переменную my_array и загружаем в нее данные из файла train_vector_1.csv
print(type(my_array)) # Выводим на экран тип переменной my_array

<class 'numpy.ndarray'>


### Задача 2

Напишите код, который считает среднее значение всех элементов массива (без использования встроенных функций np.mean и т. д.). Для решения задачи воспользуйтесь циклом.
* С помощью команды %%timeit отобразите время выполнения написанного кода.
* Преобразуйте массив my_array в список (с помощью метода list()), сохраните его в переменной my_list.
* В новой ячейке посчитайте среднее значение всех элементов списка (воспользуйтесь тем же кодом, что и для массива).
* Командой %%timeit отобразите время выполнения и этой ячейки.

**Решение:**

In [ ]:
%%timeit -n 5
summa = 0 # Создаем переменную, в которой будем сумму элементов массива
for idx, elem in enumerate(my_array): # Проходим по всем элементам массива
  summa += elem # Увеличиваем сумму на значение текущего элемента
mean_value = summa / (idx + 1) # Считаем среднее значение элементов массива
print("среднее значение массива: ", mean_value)

среднее значение массива:  3.057333333333334
среднее значение массива:  3.057333333333334
среднее значение массива:  3.057333333333334
среднее значение массива:  3.057333333333334
среднее значение массива:  3.057333333333334
среднее значение массива:  3.057333333333334
среднее значение массива:  3.057333333333334
среднее значение массива:  3.057333333333334
среднее значение массива:  3.057333333333334
среднее значение массива:  3.057333333333334
среднее значение массива:  3.057333333333334
среднее значение массива:  3.057333333333334
среднее значение массива:  3.057333333333334
среднее значение массива:  3.057333333333334
среднее значение массива:  3.057333333333334
5 loops, best of 3: 109 µs per loop


In [ ]:
my_list = list(my_array) # Создаем список из массива

In [ ]:
%%timeit -n 5
summa = 0 # Создаем переменную, в которой будем сумму элементов массива
for idx, elem in enumerate(my_list): # Проходим по всем элементам массива
  summa += elem # Увеличиваем сумму на значение текущего элемента
mean_value = summa / (idx + 1) # Считаем среднее значение элементов массива
print("среднее значение массива: ", mean_value)

среднее значение массива:  3.057333333333334
среднее значение массива:  3.057333333333334
среднее значение массива:  3.057333333333334
среднее значение массива:  3.057333333333334
среднее значение массива:  3.057333333333334
среднее значение массива:  3.057333333333334
среднее значение массива:  3.057333333333334
среднее значение массива:  3.057333333333334
среднее значение массива:  3.057333333333334
среднее значение массива:  3.057333333333334
среднее значение массива:  3.057333333333334
среднее значение массива:  3.057333333333334
среднее значение массива:  3.057333333333334
среднее значение массива:  3.057333333333334
среднее значение массива:  3.057333333333334
5 loops, best of 3: 61.8 µs per loop


### Задача 3

Подгрузите файл **iris.csv** с помощью встроенной функции **np.loadtxt**. Назовите его my_2d_array. Напишите код, который считает сумму элементов массива по столбцам (для решения данной задачи воспользуйтесь разделом ноутбук "Операции с двумерными массивами и встроенные методы").

**Решение:**

In [ ]:
my_2d_array = np.loadtxt('iris.csv', delimiter=',', skiprows=1) # Создаем переменную my_2d_array и загружаем в нее данные из файла iris.csv

In [ ]:
my_2d_array

array([[0.00e+00, 5.10e+00, 3.50e+00, 1.40e+00, 2.00e-01],
       [1.00e+00, 4.90e+00, 3.00e+00, 1.40e+00, 2.00e-01],
       [2.00e+00, 4.70e+00, 3.20e+00, 1.30e+00, 2.00e-01],
       [3.00e+00, 4.60e+00, 3.10e+00, 1.50e+00, 2.00e-01],
       [4.00e+00, 5.00e+00, 3.60e+00, 1.40e+00, 2.00e-01],
       [5.00e+00, 5.40e+00, 3.90e+00, 1.70e+00, 4.00e-01],
       [6.00e+00, 4.60e+00, 3.40e+00, 1.40e+00, 3.00e-01],
       [7.00e+00, 5.00e+00, 3.40e+00, 1.50e+00, 2.00e-01],
       [8.00e+00, 4.40e+00, 2.90e+00, 1.40e+00, 2.00e-01],
       [9.00e+00, 4.90e+00, 3.10e+00, 1.50e+00, 1.00e-01],
       [1.00e+01, 5.40e+00, 3.70e+00, 1.50e+00, 2.00e-01],
       [1.10e+01, 4.80e+00, 3.40e+00, 1.60e+00, 2.00e-01],
       [1.20e+01, 4.80e+00, 3.00e+00, 1.40e+00, 1.00e-01],
       [1.30e+01, 4.30e+00, 3.00e+00, 1.10e+00, 1.00e-01],
       [1.40e+01, 5.80e+00, 4.00e+00, 1.20e+00, 2.00e-01],
       [1.50e+01, 5.70e+00, 4.40e+00, 1.50e+00, 4.00e-01],
       [1.60e+01, 5.40e+00, 3.90e+00, 1.30e+00, 4.00e-01

In [ ]:
my_2d_array.sum(axis = 0) # Считаем сумму элементов по столбцам

array([11175. ,   876.5,   458.6,   563.7,   179.9])

### Задача 4 

* Используя библиотеку numpy, создайте массив 3x3, значения которого находятся в диапазоне от 11 до 40 (раздел "Семплирование из распределений"). 

* Не используя цикл for,  выведите на экран список элементов, которые меньше 20 (раздел "Индексация").

* Просуммируйте все элементы, не используя цикл for (раздел "Встроенные методы").


**Решение:**

In [ ]:
array_4 = np.random.randint(11,41,(3,3)) # Создаем переменную array_4 и записываем в нее массив размером 3 на 3 со значениями из диапазона от 11 до 41 (int)
print(array_4) # Выводим на экран сам массив
print() # Пустая строка
print("<20: ", array_4[array_4<20]) # Выводим все элементы массива, значения которых меньше 20
print() # Пустая строка
print("сумма:", array_4.sum()) # Выводим на экран сумму всех элементов массива

[[27 31 15]
 [28 19 36]
 [12 12 11]]

<20:  [15 19 12 12 11]

сумма: 191


### Задача 5

* Создайте массив, который будет содержать списки с именем студента(str), его возрастом(int) и средней оценкой(float) (обратите внимание на пример с занятия со списком автомобильных регионов).
* Отсортируйте такой массив (обратите внимание на параметр order метода sort()).
* Замените значение, отвечающее за возраст, у всех студентов на одно и то же, например, 10. Отсортируйте такой массив. 

**Решение:**

In [ ]:
dtype = [('Имя', '<U8'), ('Возраст', np.int32), ('Ср. оценка', np.float32)]  # Сформируем список, в котором укажем типы данных и имена столбцов для создаваемого массива
values = [('Егор', 22, 3.7), ('Максим', 19, 4.7), ('Сергей', 24, 4.2), ('Светлана', 19, 4.0), ('Наталья', 22, 3.8)] # Создадим список со значениями, которые добавим в создаваемый массив
array_5 = np.array(values, dtype = dtype) # Создадим numpy-массив со значениями из списка values (и укажем тип и название столбцов в параметре dtype)
print(array_5)

[('Егор', 22, 3.7) ('Максим', 19, 4.7) ('Сергей', 24, 4.2)
 ('Светлана', 19, 4. ) ('Наталья', 22, 3.8)]


In [ ]:
array_5.sort(order = 'Возраст') # Отсортируем массив по возрасту
print(array_5) # Выведем отсортированный массив

[('Максим', 19, 4.7) ('Светлана', 19, 4. ) ('Егор', 22, 3.7)
 ('Наталья', 22, 3.8) ('Сергей', 24, 4.2)]


In [ ]:
array_5['Возраст'] = 19 # Заменим значение возраст у всех студентов на 19
array_5.sort(order = 'Возраст') # Вновь отсортируем массив по возрасту
print(array_5) # Выведем отсортированный массив

[('Егор', 19, 3.7) ('Максим', 19, 4.7) ('Наталья', 19, 3.8)
 ('Светлана', 19, 4. ) ('Сергей', 19, 4.2)]
