<a href="https://colab.research.google.com/github/ShutTheFuckUpDonny/AI_course/blob/master/%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8F_02_Numpy/Numpy_%D0%A0%D0%B0%D0%B7%D0%B1%D0%BE%D1%80_%D0%B4%D0%BE%D0%BC%D0%B0%D1%88%D0%BD%D0%B5%D0%B3%D0%BE_%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D1%8F_Ultra_Pro_%D0%A3%D0%BD%D0%B8%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D1%82%D0%B5%D1%82_%D0%98%D1%81%D0%BA%D1%83%D1%81%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D0%BE%D0%B3%D0%BE_%D0%98%D0%BD%D1%82%D0%B5%D0%BB%D0%BB%D0%B5%D0%BA%D1%82%D0%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Задача 1

Создайте единичную матрицу размером 5*5.

**Должна получиться матрица вида**

**1** 0 0 0 0 

0 **1** 0 0 0 

0 0 **1** 0 0 

0 0 0 **1** 0 

0 0 0 0 **1** 

**Действовать можно двумя путями:**

1. Используя соответствующий метод Numpy. (О нем не говорилось в занятии. Стоит обратиться к документации Numpy).
2. Если первый вариант сложный, можно создать массив из нулей, используя метод, о котором говорилось в занятии. В цикле заменить все элементы по диагонали на единицы. 






**Решение:**

In [ ]:
import numpy as np

arr = np.eye(5) #Метод для создания данной матрицы
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
arr = np.zeros((5, 5)) #Создаем нулевую матрицу

#Проходим в цикле и меняем все значения главной диагонали на 1
for i in range(5):
  arr[i][i] = 1

print(arr) #Выводим массив

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


###Задача 2

Создайте массив из случайных значений из стандартного нормального распределения размера 6 на 6. 

Разверните массив таким образом, чтобы его размер стал 36 на 1.
Найдите среднее значение элементов массива.

**Разрешается использовать только методы Numpy. (Циклы и условия запрещены)**.

**Решение:**

In [ ]:
arr = np.random.normal(size = (6, 6)) #Создаем массив из стандартного нормально распределения размером 6 на 6
arr = arr.reshape(36, 1) #Разворачиваем массив

arr.mean() #Находим среднее значение


0.1719872730380673

###Задача 3

Создайте массив из 20 любых случайных значений, используя метод Numpy.
При помощи срезов и операций с массивами найдите значения производных для созданного массива.

**Решение:**

In [ ]:
arr = np.random.randint(0, 100, size = 20) #Создаем случайный массив
print('Созданный массив: ', arr) #Выводим информацию 
arr_diff = arr[1:] - arr[:-1] #Считаем производные
print('Его производные: ', arr_diff) #Выводим информацию 

Созданный массив:  [81  5 13 69  6 68  9 70  1 98 59 19  2 32 47 54 55 98 26 40]
Его производные:  [-76   8  56 -63  62 -59  61 -69  97 -39 -40 -17  30  15   7   1  43 -72
  14]


###Задача 4

Дано выражение

Y = A * X * C

Создайте три случайных массива A, C, X. Размерности должны позволять выполнить матричное умножение согласно формуле. На выходе должен получиться массив Y с размерностью (5, 18). (Остальные размерности возьмите на свое усмотрение).

**Решение:**

In [ ]:
A = np.random.randint(0, 100, size = (5, 24))
print('Созданный массив A: \n', A, '\n\n')
X = np.random.randint(0, 100, size = (24, 20))
print('Созданный массив X: \n', X, '\n\n')
C = np.random.randint(0, 100, size = (20, 18))
print('Созданный массив C: \n', C, '\n\n')

print('Результат произведения матриц: \n', np.dot(np.dot(A, X), C))

Созданный массив A: 
 [[11 16 85 42 53  4 37 43 55 32 87 25 54 66 33 43 17 28 22  1 30 67 57 71]
 [75 57 69 43 85 95 37 39 98  9 93 55 13 44 63 64 18  4 52 30 98 28 33 59]
 [14 62 73 90 28 27 16 34 80 35 16  6 27 39 37 88  1 99 10 27 60 93 45 60]
 [15 20 82  8 87 43  4 60 45 63 40 43 12 66 88 10 26  0 72 10 48 31 15 37]
 [25 92 10 76 58 87 54 26 15 27 81 77 55 17 17 81 53 96  5 53 50 84  7  2]] 


Созданный массив X: 
 [[41 39 94 40 97 40  3 19 74 21 35 27  5 50 67 29 76 68  6 49]
 [88 29 86 32 31 42 25 21 90 58 70 42 37 48 15 89 76 50 47 92]
 [31 40 10 56 28 86 91 20 37 14 69 63 17 17  5 22 35 72 33 20]
 [76 54  6 51 34  0  4  6 92 11 24 95 70 57 86  4 32  7 85 88]
 [61 16 47 24 11 10 52 17 28  5  6 84 28 22 33 36 41  7 21  4]
 [77 58 50  4 29 26 51 32 79 81 45 15 44 93 60 35 86 43  5 47]
 [13 62 31  2 78 82 42 93 96 77 97 59 35 39 25 49 34 78 34  5]
 [63  8 49 62 61 33 76 39 17 83  5 26 43 91 93 25 97 84  2 26]
 [ 5 23 17 18  5 10 90 54 47 89 38 28 79 33 80 27 34  5 47 19]
 [65 64 46

###Задача 5

Загрузите какой-либо файл с данными (таблица Excel с Вашего компьютера, сохраненная в формате csv, или таблица из Интернета). Выведите следующее:

1. Всю информацию из файла в ячейку. 
2. Размерность данных. 
3. Среднее арифметическое от всех числовых значений (если есть).
4. Число столбов. 
5. Число строк.
6. Типы данных всех значений. 

**Решение:**

In [ ]:
arr = np.loadtxt('iris.csv', delimiter=',', skiprows=1) #Загружаем данные

In [ ]:
arr #Выводим данные 

[[0.00e+00 5.10e+00 3.50e+00 1.40e+00 2.00e-01]
 [1.00e+00 4.90e+00 3.00e+00 1.40e+00 2.00e-01]
 [2.00e+00 4.70e+00 3.20e+00 1.30e+00 2.00e-01]
 [3.00e+00 4.60e+00 3.10e+00 1.50e+00 2.00e-01]
 [4.00e+00 5.00e+00 3.60e+00 1.40e+00 2.00e-01]
 [5.00e+00 5.40e+00 3.90e+00 1.70e+00 4.00e-01]
 [6.00e+00 4.60e+00 3.40e+00 1.40e+00 3.00e-01]
 [7.00e+00 5.00e+00 3.40e+00 1.50e+00 2.00e-01]
 [8.00e+00 4.40e+00 2.90e+00 1.40e+00 2.00e-01]
 [9.00e+00 4.90e+00 3.10e+00 1.50e+00 1.00e-01]
 [1.00e+01 5.40e+00 3.70e+00 1.50e+00 2.00e-01]
 [1.10e+01 4.80e+00 3.40e+00 1.60e+00 2.00e-01]
 [1.20e+01 4.80e+00 3.00e+00 1.40e+00 1.00e-01]
 [1.30e+01 4.30e+00 3.00e+00 1.10e+00 1.00e-01]
 [1.40e+01 5.80e+00 4.00e+00 1.20e+00 2.00e-01]
 [1.50e+01 5.70e+00 4.40e+00 1.50e+00 4.00e-01]
 [1.60e+01 5.40e+00 3.90e+00 1.30e+00 4.00e-01]
 [1.70e+01 5.10e+00 3.50e+00 1.40e+00 3.00e-01]
 [1.80e+01 5.70e+00 3.80e+00 1.70e+00 3.00e-01]
 [1.90e+01 5.10e+00 3.80e+00 1.50e+00 3.00e-01]
 [2.00e+01 5.40e+00 3.40e+00 1.70e+00 2.

In [ ]:
arr.shape #Выводим размерность

(150, 5)

In [ ]:
arr.mean() #Выводим среднее

17.671599999999998

In [ ]:
arr.shape[1] #Выводим число столбцов

5

In [ ]:
arr.shape[0] #Выводим число строк

150

In [ ]:
arr.dtype #Выводим тип данных

dtype('float64')