<a href="https://colab.research.google.com/github/ShutTheFuckUpDonny/AI_course/blob/master/%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8F_02_Numpy/Numpy_%D0%A0%D0%B0%D0%B7%D0%B1%D0%BE%D1%80_%D0%B4%D0%BE%D0%BC%D0%B0%D1%88%D0%BD%D0%B5%D0%B3%D0%BE_%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D1%8F_Pro_%D0%A3%D0%BD%D0%B8%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D1%82%D0%B5%D1%82_%D0%98%D1%81%D0%BA%D1%83%D1%81%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D0%BE%D0%B3%D0%BE_%D0%98%D0%BD%D1%82%D0%B5%D0%BB%D0%BB%D0%B5%D0%BA%D1%82%D0%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Задача 1

* Подгрузите массив **iris.csv** и назовите его my_array. 

* Создайте двумерный массив из случайных чисел той же размерности, что и my_array (раздел "Семплирование из распределений", потребуется использовать размерность массива my_array).

* Назовите его my_generated_array.

**Решение:**

In [ ]:
import numpy as np
my_array = np.loadtxt('iris.csv', delimiter=',', skiprows=1) # Создаем переменную my_generated_array и записываем в нее данные из файла iris.csv

In [ ]:
my_array.shape

(150, 5)

In [ ]:
my_generated_array = np.random.random(my_array.shape) # Создаем массив той же размерности, что и my_array
print(my_array.shape) # Выводим размерность массива my_array
print(my_generated_array.shape) # Выводим размерность массива my_generated_array

(150, 5)
(150, 5)


### Задача 2

* Выполните поэлементное умножение my_array на my_generated_array (раздел "Векторные операции").

* Склейте массивы my_array и my_generated_array в один (могут помочь методы np.concatenate, np.vstack, np.hstack).

* Возьмите склеенный массив и разделите его на равные части (больше двух). Можно сделать вручную через циклы либо воспользоваться методом vsplit.

**Решение:**

In [ ]:
prod_array = (my_array * my_generated_array) # Выполняем поэлементное умножение элементов массива
prod_array[:5]

array([[0.        , 2.05306026, 3.17611085, 0.66817581, 0.04433603],
       [0.01032647, 3.96935089, 1.15188406, 0.02836379, 0.10801529],
       [0.75484703, 1.0542058 , 3.04912438, 1.23204373, 0.07857828],
       [2.9463855 , 3.90495301, 2.62008503, 1.00189219, 0.14061665],
       [0.32086139, 2.72670334, 2.88053015, 0.69141782, 0.05592068]])

In [ ]:
c1_array = np.concatenate((my_array, my_generated_array)) # Склеиваем массивы методом .concatenate()
print(c1_array.shape) # Выводим размерность нового массива
c2_array = np.vstack((my_array, my_generated_array)) # Склеиваем массивы методом .vstack() построчно
print(c2_array.shape) # Выводим размерность нового массива
c3_array = np.hstack((my_array, my_generated_array)) # Склеиваем массивы методом .hstack() построчно
print(c3_array.shape) # Выводим размерность нового массива

(300, 5)
(300, 5)
(150, 10)


In [ ]:
list_arrays = np.vsplit(c1_array, 10) # Разделяем массив на 5 частей
print(len(list_arrays)) # Выводим на экран длину списка list_arrays
print(list_arrays[0].shape) # Выводим на экран размерность первого элемента list_arrays

10
(30, 5)


### Задача 3

* Найдите все элементы массива my_array, которые больше трех и меньше 5 одновременно. Используйте методологию подвыборки массива с условием (раздел "Индексация").

**Решение:**

In [ ]:
my_array[(my_array > 3) & (my_array < 5)]

array([3.5, 4.9, 4.7, 3.2, 4.6, 3.1, 4. , 3.6, 3.9, 4.6, 3.4, 3.4, 4.4,
       4.9, 3.1, 3.7, 4.8, 3.4, 4.8, 4.3, 4. , 4.4, 3.9, 3.5, 3.8, 3.8,
       3.4, 3.7, 4.6, 3.6, 3.3, 4.8, 3.4, 3.4, 3.5, 3.4, 4.7, 3.2, 4.8,
       3.1, 3.4, 4.1, 4.2, 4.9, 3.1, 3.2, 3.5, 4.9, 3.6, 4.4, 3.4, 3.5,
       4.5, 4.4, 3.2, 3.5, 3.8, 4.8, 3.8, 4.6, 3.2, 3.7, 3.3, 3.2, 4.7,
       3.2, 4.5, 3.1, 4.9, 4. , 4.6, 4.5, 3.3, 4.7, 4.9, 3.3, 4.6, 3.9,
       3.5, 4.2, 4. , 4.7, 3.6, 3.1, 4.4, 4.5, 4.1, 4.5, 3.9, 3.2, 4.8,
       4. , 4.9, 4.7, 4.3, 4.4, 4.8, 4.5, 3.5, 3.8, 3.7, 3.9, 4.5, 3.4,
       4.5, 3.1, 4.7, 4.4, 4.1, 4. , 4.4, 4.6, 4. , 3.3, 4.2, 4.2, 4.2,
       4.3, 4.1, 3.3, 4.9, 4.5, 3.6, 3.2, 3.2, 3.8, 3.2, 4.9, 4.9, 3.3,
       3.2, 4.8, 4.9, 3.8, 3.4, 3.1, 4.8, 3.1, 3.1, 3.1, 3.2, 3.3, 3.4])

### Задача 4

Создайте трехмерный массив размера 2 на 3 на 4, состоящий из случайных ВЕЩЕСТВЕННЫХ чисел от 15 до 37. Используйте встроенные методы библиотеки  np.random.

**Решение:**

In [ ]:
rnd_array = np.random.uniform(15, 37, (2,3,4)) # Создаем массив из случайных вещественных чисел от 15 до 37 размерностью 2 на 3 на 4
print(rnd_array) # Отображаем созданный массив

[[[17.57084123 24.87265668 31.03420172 36.96985425]
  [30.48414655 34.20719299 22.80018747 24.17688222]
  [22.94463262 36.02442465 25.16278591 17.64246521]]

 [[31.37706367 22.35541348 25.84634805 22.0956851 ]
  [19.76517896 23.73085426 25.16278501 20.34991453]
  [26.50514742 16.42507819 23.02659051 30.75183197]]]


### Задача 5

Используя массив из предыдущей задачи, преобразуйте его в новый массив со следующими значениями:

    * "small", если значения меньше 20
    * "medium", если значения в промежутке [20, 30]
    * "large", если значения больше 30

**Решение:**

In [ ]:
new_array = np.full((2,3,4), 'medium', dtype='<U32') # Создаем массив размерности 2 на 3 на 4, заполненный словом medium
new_array[rnd_array < 20] = 'small' # Меняем значение в массива на small для тех элемнтов, у которых выполняется условие rnd_array < 20
new_array[rnd_array > 30] = 'large' # Меняем значение в массива на large для тех элемнтов, у которых выполняется условие rnd_array > 30
print(rnd_array) # Отображаем массив из предыдущей задачи
print()
print(new_array) # Отображаем сформированный массив

[[[17.57084123 24.87265668 31.03420172 36.96985425]
  [30.48414655 34.20719299 22.80018747 24.17688222]
  [22.94463262 36.02442465 25.16278591 17.64246521]]

 [[31.37706367 22.35541348 25.84634805 22.0956851 ]
  [19.76517896 23.73085426 25.16278501 20.34991453]
  [26.50514742 16.42507819 23.02659051 30.75183197]]]

[[['small' 'medium' 'large' 'large']
  ['large' 'large' 'medium' 'medium']
  ['medium' 'large' 'medium' 'small']]

 [['large' 'medium' 'medium' 'medium']
  ['small' 'medium' 'medium' 'medium']
  ['medium' 'small' 'medium' 'large']]]
