<a href="https://colab.research.google.com/github/ShutTheFuckUpDonny/AI_course/blob/master/%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8F_02_Numpy/Pro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Задача 1

* Подгрузите массив **iris.csv** и назовите его my_array. 

* Создайте двумерный массив из случайных чисел той же размерности, что и my_array (раздел "Семплирование из распределений", потребуется использовать размерность массива my_array).

* Назовите его my_generated_array.

**Решение:**

In [ ]:
import numpy as np

my_array = np.loadtxt('iris.csv', delimiter=',', skiprows=1)
print(my_array.shape)
my_generated_array = np.random.random((my_array.shape))
#print(my_generated_array)
print(my_generated_array.shape)

(150, 5)
(150, 5)


### Задача 2

* Выполните поэлементное умножение my_array на my_generated_array (раздел "векторные операции").

* Склейте массивы my_array, my_generated_array в один (могут помочь методы np.concatenate, np.vstack, np.hstack).

* Возьмите склеенный массив и разделите его на равные части (больше двух). Можно сделать вручную через циклы либо воспользоваться методом vsplit.

**Решение:**

In [ ]:
res_arr = my_array * my_generated_array
# опционально можно удалить "#" для проверки результата
#print(res_arr)
conc_arr = np.concatenate([my_array, my_generated_array])
np.vsplit(conc_arr, 75)

### Задача 3

* Найдите все элементы массива my_array, которые больше трех и меньше 5 одновременно. Используйте методологию подвыборки массива с условием (раздел "Индексация").

**Решение:**

In [ ]:
my_array[(my_array > 3) & (my_array < 5)]

### Задача 4

Создайте трехмерный массив размера 2 на 3 на 4, состоящий из случайных ВЕЩЕСТВЕННЫХ чисел от 15 до 37. Используйте встроенные методы библиотеки  np.random.

**Решение:**

In [ ]:
task_4_arr = np.random.uniform(15, 37, (2,3,4))
print(task_4_arr)
print()
print(task_4_arr[:,0][0][1])

[[[15.54064718 30.78127384 32.75799912 28.72809423]
  [19.65461757 20.20971106 35.90976446 31.91579375]
  [30.53576479 22.64064574 20.22498457 23.86547571]]

 [[34.99934748 21.43504049 29.02192848 25.52505717]
  [36.89266465 26.14614775 28.3363305  33.45931962]
  [31.26503774 27.26542044 19.0546872  29.06882471]]]

30.781273838961525


### Задача 5

Используя массив из предыдущей задачи, преобразуйте его в новый массив со следующими значениями:

    * "small", если значения меньше 20
    * "medium", если значения в промежутке [20, 30]
    * "large", если значения больше 30

**Решение:**

In [ ]:
'''Хотел найти лучшее решение, но не смог. Пытался через np.place и 
numpy.apply_along_axis, но возникали ошибки из-за несоответствия типов данных
или размерности массива. Подскажите более изящный способ решения задачи'''
A = []
for i in np.nditer(task_4_arr):
  if i < 20:
    A.append('small')
  elif 20 <= i <= 30:
    A.append('medium')
  else:
    A.append('large')
A = np.array(A).reshape(2,3,4)
print(A)       

[[['small' 'large' 'large' 'medium']
  ['small' 'medium' 'large' 'large']
  ['large' 'medium' 'medium' 'medium']]

 [['large' 'medium' 'medium' 'medium']
  ['large' 'medium' 'medium' 'large']
  ['large' 'medium' 'small' 'medium']]]
