<a href="https://colab.research.google.com/github/ShutTheFuckUpDonny/AI_course/blob/master/%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8F_02_Numpy/Ultra_Pro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Задача 1

Создайте единичную матрицу размером 5*5.

**Должна получиться матрица вида:**

**1** 0 0 0 0 

0 **1** 0 0 0 

0 0 **1** 0 0 

0 0 0 **1** 0 

0 0 0 0 **1** 

**Действовать можно двумя путями:**

1. Используя соответствующий метод Numpy. (О нем не говорилось в занятии. Стоит обратиться к документации Numpy)
2. Если первый вариант сложный, можно создать массив из нулей, используя метод, о котором говорилось в занятии. В цикле заменить все элементы по диагонали на единицы. 






**Решение:**

In [ ]:
import numpy as np

np.eye(5, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

###Задача 2

Создайте массив из случайных значений из стандартного нормального распределения размера 6 на 6. 

"Разверните" массив таким образом, чтобы его размер стал 36 на 1
Найдите среднее значение элементов массива

**Разрешается использовать только методы Numpy. (Циклы и условия запрещены)**

**Решение:**

In [ ]:
arr = np.random.normal(0,1,(6,6)).round(2) # округление опционально, для улучшения восприятия
print(arr)
print()
print(arr.reshape(36,).mean())

[[-0.43 -0.52 -0.03 -0.34  0.77 -0.01]
 [-2.53  0.92 -0.82 -0.19 -1.8  -0.36]
 [ 0.01 -0.41  1.88 -0.68 -1.69  0.72]
 [-1.22  1.65 -0.2   0.58 -0.1  -0.1 ]
 [-0.65 -1.42 -1.71 -0.77  0.47 -1.75]
 [-0.32  0.09 -1.33 -0.13 -1.31 -0.27]]

-0.38888888888888895


###Задача 3

Создайте массив из 20 любых случайных значений, используя метод Numpy.
При помощи срезов и операций с массивами найдите значения производных для созданного массива

**Решение:**

In [ ]:
arr_diff = np.random.random((20)).round(2)
print(arr_diff)
print()
# первый и самый простой способ
print(np.diff(arr_diff))
print()
# второй способ
diff_list = []
for i in range(len(arr_diff)):
  try:
    res = arr_diff[i+1] - arr_diff[i]
    diff_list.append(res.round(2))
  except IndexError:
    pass
print(np.array(diff_list))      




[0.58 0.01 0.67 0.21 0.69 0.07 0.17 0.8  0.73 0.5  0.02 0.08 0.27 0.06
 0.44 0.78 0.08 0.8  0.96 0.1 ]

[-0.57  0.66 -0.46  0.48 -0.62  0.1   0.63 -0.07 -0.23 -0.48  0.06  0.19
 -0.21  0.38  0.34 -0.7   0.72  0.16 -0.86]

[-0.57  0.66 -0.46  0.48 -0.62  0.1   0.63 -0.07 -0.23 -0.48  0.06  0.19
 -0.21  0.38  0.34 -0.7   0.72  0.16 -0.86]


###Задача 4

Дано выражение

Y = A * X * C

Создайте три случайных массива: A, C, X. Размерности должны позволять выполнить матричное умножение, согласно формуле. На выходе должен получиться массив Y с размерностью (5, 18). (Остальные размерности возьмите на свое усмотрение)

**Решение:**

In [ ]:
A = np.random.randint(1, 3, (5, 3))
X = np.random.randint(1, 3, (3, 6))
C = np.random.randint(1, 3, (6, 18))
Y = A.dot(X).dot(C)
print(Y.shape)
Y

(5, 18)


array([[61, 62, 40, 58, 47, 44, 40, 58, 52, 57, 63, 45, 45, 46, 39, 50,
        58, 57],
       [61, 62, 40, 58, 47, 44, 40, 58, 52, 57, 63, 45, 45, 46, 39, 50,
        58, 57],
       [61, 61, 39, 58, 48, 44, 39, 58, 53, 58, 63, 44, 44, 46, 39, 51,
        58, 58],
       [75, 76, 49, 72, 59, 54, 49, 72, 65, 71, 78, 55, 55, 57, 48, 62,
        72, 71],
       [80, 79, 50, 74, 61, 58, 50, 74, 68, 75, 81, 57, 57, 59, 51, 67,
        74, 75]])

###Задача 5

Загрузите какой-либо файл с данными (таблица Excel с Вашего компьютера, сохранненая в формате csv, или таблица из Интернета). Выведите:

1. Всю информацию из файла в ячейку. 
2. Размерность данных 
3. Среднее арифметическое от всех числовых значений (если есть)
4. Число столбов 
5. Число строк
6. Типы данных всех значений 

**Решение:**

In [ ]:
import numpy as np
import csv 

filename = 'titanic (1).csv'
with open(filename) as f:
  reader = csv.reader(f)
  file_list = list(reader)

file_arr = np.array(file_list[:10]) # сократил до 10 строк вместо 892 фактических
print(file_arr)
print('размер массива:', file_arr.shape)

# находим числовые данные и среднее арифметическое
num_list = []
for num in np.nditer(file_arr):
  try:
    if float(num):
      num_list.append(float(num))
  except ValueError:
    pass
np.mean(num_list)

# эта задача решается с помощью .shape. Так как в случае массива с одной строкой
# при вызове .shape[1] будет ошибка 'out of index'. Возможно есть метод, что 
# возвращает количество строк и столбцов, но я не нашел его. 
print('количество строк:', file_arr.shape[0])
print('количество столбцов:', file_arr.shape[1])

file_arr.dtype



  
   



[['PassengerId' 'Survived' 'Pclass' 'Name' 'Sex' 'Age' 'SibSp' 'Parch'
  'Ticket' 'Fare' 'Cabin' 'Embarked']
 ['1' '0' '3' 'Braund, Mr. Owen Harris' 'male' '22' '1' '0' 'A/5 21171'
  '7.25' '' 'S']
 ['2' '1' '1' 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)'
  'female' '38' '1' '0' 'PC 17599' '71.2833' 'C85' 'C']
 ['3' '1' '3' 'Heikkinen, Miss. Laina' 'female' '26' '0' '0'
  'STON/O2. 3101282' '7.925' '' 'S']
 ['4' '1' '1' 'Futrelle, Mrs. Jacques Heath (Lily May Peel)' 'female'
  '35' '1' '0' '113803' '53.1' 'C123' 'S']
 ['5' '0' '3' 'Allen, Mr. William Henry' 'male' '35' '0' '0' '373450'
  '8.05' '' 'S']
 ['6' '0' '3' 'Moran, Mr. James' 'male' '' '0' '0' '330877' '8.4583' ''
  'Q']
 ['7' '0' '1' 'McCarthy, Mr. Timothy J' 'male' '54' '0' '0' '17463'
  '51.8625' 'E46' 'S']
 ['8' '0' '3' 'Palsson, Master. Gosta Leonard' 'male' '2' '3' '1'
  '349909' '21.075' '' 'S']
 ['9' '1' '3' 'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)'
  'female' '27' '0' '2' '347742' '11.1333' '' 'S']

dtype('<U51')